server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    port: 6379
    password: tian0803  #改成自己的
    host: 101.200.219.27 #改成自己的
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
ly:
  jwt:
    pubKeyPath: C:\\Users\\Administrator\\Desktop\\leyou笔记\\day16\\id_sra.pub # 公钥地址
    priKeyPath: C:\\Users\\Administrator\\Desktop\\leyou笔记\\day16\\id_sra # 私钥地址
    user: #跟cookie相关的配置
      expice: 30 #过期时间
      cookieName: LY_TOKEN #cookie名称
      cookieDomain: leyou.com #cookie的域
      minRefreshInterval: 15 #刷新token