server:
  port: 8084
spring:
  application:
    name: page-service
    #把thymeleaf 缓存关闭
  thymeleaf:
    cache: false
ly:
  static:
    itemDir: F:\nginx-1.12.2\html\item  #改成我们自己的nginx目录地址
    itemTemplate: item
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
rocketmq:
  name-server: 127.0.0.1:9876